name: Temporarily Lock Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to lock'
        required: true
        default: 'main'

jobs:
  lock-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: Apply temporary lock
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection/required_pull_request_reviews \
            -d "{\"required_approving_review_count\": 6}"
              #-d '{
              #"required_status_checks": {
                #"strict": true,
                #"contexts": []
                #},
              #"enforce_admins": false,
              #"required_pull_request_reviews": {
              #  "dismiss_stale_reviews": false,
              #  "require_code_owner_reviews": false,
              #  "required_approving_review_count": 6
              #}
              #"restrictions": null,
              #"allow_force_pushes": false,
              #"allow_deletions": false
          echo "✅ Applied temporary lock (requires 99 reviews, disables admin override)."

      - name: Wait 20 seconds
        run: sleep 20

      - name: Restore original protection
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection/required_pull_request_reviews \
            -d "{\"required_approving_review_count\": 1}"
          echo "🔓 Original protection restored."

