name: Merge Gate Controller

on:
  workflow_dispatch:
    inputs:
      gate_action:
        description: 'Set gate to "pass" (unlock merges) or "fail" (lock merges)'
        required: true
        type: choice
        options:
          - pass
          - fail

permissions:
  contents: read

jobs:
  merge_gate_check:
    runs-on: ubuntu-latest
    environment: Merge Gate master

    steps:
      - name: Evaluate Gate Action
        run: |
          ACTION="${{ github.event.inputs.gate_action }}"
          echo "Received gate action: $ACTION"

          if [[ "$ACTION" == "fail" ]]; then
            echo "Gate set to FAIL. Blocking merges by failing this required check."
            exit 1 # Fail the job
          elif [[ "$ACTION" == "pass" ]]; then
            echo "Gate set to PASS. Allowing merges by passing this required check."
            exit 0 # Succeed the job
          else
            echo "Error: Invalid gate action received: $ACTION"
            exit 2 # Fail for invalid input
          fi
