name: Merge Lock API

on:
  workflow_dispatch:

permissions:
  # Default GITHUB_TOKEN permissions are not sufficient for this.
  # Permissions are granted by the PAT/App token used below.
  contents: read # Example, needed for checkout

jobs:
  lock_run_unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lock Branch 🔒
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} # Use the PAT stored as a secret
          BRANCH_NAME: main # Or your target branch e.g. 'release'
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Attempting to lock branch: $BRANCH_NAME"
          gh api \
            --method PUT "/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME/protection" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --silent \
            -f enforce_admins=true \
            -f required_status_checks=null \
            -f required_pull_request_reviews=null \
            -f restrictions=null \
            -f allow_force_pushes=false \
            -f allow_deletions=false \
            -f block_creations=false \
            -f required_linear_history=false \
            -f required_conversation_resolution=false \
            -f lock_branch=true \
            || { echo "Failed to lock branch"; exit 1; } # Exit if lock fails

          echo "Branch $BRANCH_NAME locked."

      - name: Run Critical Task
        id: critical_task
        run: |
          echo "Running the important process on locked branch..."
          sleep 30
          echo "Process finished!"
          # Replace with your actual commands

      - name: Unlock Branch 🔓
        if: always()
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} # Use the PAT stored as a secret
          BRANCH_NAME: main # Or your target branch
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Attempting to unlock branch: $BRANCH_NAME"

          gh api \
            --method PUT "/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME/protection" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --silent \
            -f enforce_admins=true \
            -f required_status_checks=null \
            -F required_pull_request_reviews=null \
            -f restrictions=null \
            -F allow_force_pushes=false \
            -F allow_deletions=false \
            -F block_creations=false \
            -F required_linear_history=false \
            -F required_conversation_resolution=false \
            -F lock_branch=false \
            || { echo "Failed to unlock branch - MANUAL INTERVENTION MAY BE REQUIRED"; exit 1; } # Exit if unlock fails

          echo "Branch $BRANCH_NAME unlocked."