name: Temporarily Lock Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to lock'
        required: true
        default: 'main'

jobs:
  lock-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: Save current protection rules
        id: get-protection
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/$REPO/branches/$BRANCH/protection \
               -o original_protection.json
          echo "Saved current protection to file."

      - name: Apply temporary lock
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection \
            -d '{
              "required_status_checks": null,
              "enforce_admins": false,
              "required_pull_request_reviews": {
                "required_approving_review_count": 99
              },
              "restrictions": null
            }'
          echo "✅ Applied temporary lock (requires 99 reviews, disables admin override)."

      - name: Wait 20 seconds
        run: sleep 20

      - name: Restore original protection
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            --data-binary @original_protection.json \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection
          echo "🔓 Original protection restored."

