name: Lock Branch and Sleep

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to lock'
        required: true
        default: 'main'

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Lock branch using GitHub API
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": null,
              "restrictions": null
            }'
          echo "Branch $BRANCH locked."

      - name: Sleep for 20 seconds
        run: sleep 20

      - name: Unlock branch using GitHub API
        if: always()
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          curl -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection
          echo "Branch $BRANCH unlocked."

