name: Merge Lock API

on:
  workflow_dispatch:

permissions:
  # Default GITHUB_TOKEN permissions are not sufficient for this.
  # Permissions are granted by the PAT/App token used below.
  contents: read # Example, needed for checkout

jobs:
  lock_run_unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lock Branch 🔒
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          BRANCH_NAME: main # Or your target branch
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Attempting to lock branch: $BRANCH_NAME"

          # Construct the JSON payload explicitly
          # Note: true, false, null are NOT quoted in JSON
          JSON_PAYLOAD=$(cat <<EOF
          {
            "required_status_checks": null,
            "enforce_admins": true,
            "required_pull_request_reviews": null,
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "block_creations": false,
            "required_linear_history": false,
            "required_conversation_resolution": false,
            "lock_branch": true
          }
          EOF
          )

          # Send the JSON payload using --input -
          echo "$JSON_PAYLOAD" | gh api \
            --method PUT "/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME/protection" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --input - \
            --silent || { echo "Failed to lock branch"; exit 1; }

          echo "Branch $BRANCH_NAME locked."

      - name: Run Critical Task
        id: critical_task
        run: |
          echo "Running the important process on locked branch..."
          sleep 30
          echo "Process finished!"
          # Replace with your actual commands

          - name: Unlock Branch 🔓
          # This condition ensures the step runs even if previous steps failed
          if: always()
          env:
            # Use the PAT stored as a secret with repo admin rights
            GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
            # Set your target branch name here
            BRANCH_NAME: main
            REPO_OWNER: ${{ github.repository_owner }}
            REPO_NAME: ${{ github.event.repository.name }}
          run: |
            echo "Attempting to unlock branch: $BRANCH_NAME"
  
            # Construct the exact JSON payload for unlocking
            # The only difference from the lock payload is "lock_branch": false
            JSON_PAYLOAD=$(cat <<EOF
            {
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": null,
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false,
              "block_creations": false,
              "required_linear_history": false,
              "required_conversation_resolution": false,
              "lock_branch": false # Set to false to unlock
            }
            EOF
            )
  
            # Send the JSON payload using --input -
            # Piping the JSON string into gh api ensures correct formatting
            echo "$JSON_PAYLOAD" | gh api \
              --method PUT "/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME/protection" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              --input - \
              --silent || { echo "Failed to unlock branch - MANUAL INTERVENTION MAY BE REQUIRED"; exit 1; } # Exit if unlock fails
  
            echo "Branch $BRANCH_NAME unlocked."